### ISSUE TITLE
pH and Dosing pumps not working after recent HA update.

### ISSUE THREAD

**Issue by justin1977justin** [tdragon/reef-pi-hass-custom#7]
Recently updated to core-2021.11.3 and supervisor-2021.10.8. My ph and dosing pump activities are now unavailable on all 5 reef-pi setups I am currently running.

**Comment by tdragon** [comment]
I'll check what can be wrong. 
Are there any errors in the log? What version you updated from?

**Comment by tdragon** [comment]
Ok, seems I found one issue that can lead to 'unavailable' status of pH and dosers. I don't use these myself, so please check if the fix helps. The fix is included in version 0.1.7

**Comment by justin1977justin** [comment]
I updated but that did not seem to make a difference. The following is what is shown in the entity window:

      This entity is currently unavailable and is an orphan to a removed, changed or dysfunctional integration or device.

The following are reef-pi issues showing in my log:

2021-11-16 13:23:04 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing reef_pi/recorder.py
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 33, in _process
platform = integration.get_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 530, in get_platform
cache[full_name] = self._import_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 535, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.reef-pi-hass-custom.recorder'
2021-11-16 13:23:04 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing reef_pi/significant_change.py
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 33, in _process
platform = integration.get_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 530, in get_platform
cache[full_name] = self._import_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 535, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.reef-pi-hass-custom.significant_change'
2021-11-16 13:23:04 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing reef_pi/system_health.py
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 33, in _process
platform = integration.get_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 530, in get_platform
cache[full_name] = self._import_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 535, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.reef-pi-hass-custom.system_health'

I am not great with the coding side but let me know if you need me to test anything.

**Comment by tdragon** [comment]
This is weird error: there is no such thing "custom_components.reef-pi-hass-custom.recorder" nor "custom_components.reef-pi-hass-custom.system_health". I don't understand why HA tries to load them. It looks like reef-pi integration installation was corrupted somehow. 

Could you check what is in your folder where the reef-pi-hass-custom is installed?
That folder should contain only files from the reef pi integration. You can download it from releases to compare. 
I am also running 2021.11.3 with the same version of python and don't see any errors in my log. I tried to add a doser into my reef-pi and it shows me a valid config.

**Comment by justin1977justin** [comment]
I checked the folder and found that everything was normal, however, I noticed that I had 2 reef-pi folders. One just named reef-pi and another named reef-pi-hass-custom. I'm guessing this was an old folder from the initial versions of reef-pi. I deleted that folder and restarted and everything is normal again. Thanks for the help.
